### ISSUE TITLE
undefined method `run_hook' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by evanleck** [fredjean/middleman-s3_sync#95]
Hi,

After upgrading from 3.0.47 to 3.3.3 I keep running into the same error part way through the sync operation:

```
/Users/evan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/middleman-s3_sync-3.3.3/lib/middleman/s3_sync.rb:43:in `sync': undefined method `run_hook' for nil:NilClass (NoMethodError)
  from /Users/evan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/middleman-s3_sync-3.3.3/lib/middleman-s3_sync/extension.rb:48:in `after_build'
  from /Users/evan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/middleman-core-3.4.0/lib/middleman-core/extension.rb:160:in `block in bind_after_build'
  from /Users/evan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/uber-0.0.15/lib/uber/options.rb:96:in `instance_exec'
  from /Users/evan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/uber-0.0.15/lib/uber/options.rb:96:in `proc!'
  from /Users/evan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/uber-0.0.15/lib/uber/options.rb:82:in `evaluate_for'
  from /Users/evan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/uber-0.0.15/lib/uber/options.rb:60:in `call'
  from /Users/evan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/hooks-0.4.1/lib/hooks/hook.rb:59:in `evaluate_callback'
  from /Users/evan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/hooks-0.4.1/lib/hooks/hook.rb:55:in `execute_callback'
  from /Users/evan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/hooks-0.4.1/lib/hooks/hook.rb:40:in `block in run'
  from /Users/evan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/hooks-0.4.1/lib/hooks/hook.rb:39:in `each'
  from /Users/evan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/hooks-0.4.1/lib/hooks/hook.rb:39:in `inject'
  from /Users/evan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/hooks-0.4.1/lib/hooks/hook.rb:39:in `run'
  from /Users/evan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/hooks-0.4.1/lib/hooks.rb:55:in `run_hook_for'
  from /Users/evan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/hooks-0.4.1/lib/hooks/instance_hooks.rb:6:in `run_hook'
  from /Users/evan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/middleman-core-3.4.0/lib/middleman-core/cli/build.rb:72:in `build'
  from /Users/evan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
  from /Users/evan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
  from /Users/evan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
  from /Users/evan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
  from /Users/evan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/middleman-core-3.4.0/lib/middleman-core/cli.rb:72:in `method_missing'
  from /Users/evan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:29:in `run'
  from /Users/evan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:126:in `run'
  from /Users/evan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
  from /Users/evan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
  from /Users/evan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
  from /Users/evan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/middleman-core-3.4.0/lib/middleman-core/cli.rb:20:in `start'
  from /Users/evan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/middleman-core-3.4.0/bin/middleman:18:in `<top (required)>'
  from /Users/evan/.rbenv/versions/2.2.2/bin/middleman:23:in `load'
  from /Users/evan/.rbenv/versions/2.2.2/bin/middleman:23:in `<main>'
```

My Gemfile.lock looks like this:

```
GEM
  remote: https://rubygems.org/
  specs:
    activesupport (4.2.4)
      i18n (~> 0.7)
      json (~> 1.7, >= 1.7.7)
      minitest (~> 5.1)
      thread_safe (~> 0.3, >= 0.3.4)
      tzinfo (~> 1.1)
    ansi (1.5.0)
    autoprefixer-rails (6.0.3)
      execjs
      json
    bootstrap-sass (3.3.5.1)
      autoprefixer-rails (>= 5.0.0.1)
      sass (>= 3.3.0)
    builder (3.2.2)
    capybara (2.4.4)
      mime-types (>= 1.16)
      nokogiri (>= 1.3.3)
      rack (>= 1.0.0)
      rack-test (>= 0.5.4)
      xpath (~> 2.0)
    chunky_png (1.3.4)
    coffee-script (2.4.1)
      coffee-script-source
      execjs
    coffee-script-source (1.9.1.1)
    compass (1.0.3)
      chunky_png (~> 1.2)
      compass-core (~> 1.0.2)
      compass-import-once (~> 1.0.5)
      rb-fsevent (>= 0.9.3)
      rb-inotify (>= 0.9)
      sass (>= 3.3.13, < 3.5)
    compass-core (1.0.3)
      multi_json (~> 1.0)
      sass (>= 3.3.0, < 3.5)
    compass-import-once (1.0.5)
      sass (>= 3.2, < 3.5)
    em-websocket (0.5.1)
      eventmachine (>= 0.12.9)
      http_parser.rb (~> 0.6.0)
    erubis (2.7.0)
    eventmachine (1.0.8)
    excon (0.45.4)
    execjs (2.6.0)
    ffi (1.9.10)
    fog-aws (0.7.6)
      fog-core (~> 1.27)
      fog-json (~> 1.0)
      fog-xml (~> 0.1)
      ipaddress (~> 0.8)
    fog-core (1.32.1)
      builder
      excon (~> 0.45)
      formatador (~> 0.2)
      mime-types
      net-scp (~> 1.1)
      net-ssh (>= 2.1.3)
    fog-json (1.0.2)
      fog-core (~> 1.0)
      multi_json (~> 1.10)
    fog-xml (0.1.2)
      fog-core
      nokogiri (~> 1.5, >= 1.5.11)
    formatador (0.2.5)
    haml (4.0.7)
      tilt
    hike (1.2.3)
    hooks (0.4.1)
      uber (~> 0.0.14)
    htmlcompressor (0.2.0)
    http_parser.rb (0.6.0)
    i18n (0.7.0)
    ipaddress (0.8.0)
    json (1.8.3)
    kramdown (1.9.0)
    listen (3.0.3)
      rb-fsevent (>= 0.9.3)
      rb-inotify (>= 0.9)
    map (6.5.5)
    middleman (3.4.0)
      coffee-script (~> 2.2)
      compass (>= 1.0.0, < 2.0.0)
      compass-import-once (= 1.0.5)
      execjs (~> 2.0)
      haml (>= 4.0.5)
      kramdown (~> 1.2)
      middleman-core (= 3.4.0)
      middleman-sprockets (>= 3.1.2)
      sass (>= 3.4.0, < 4.0)
      uglifier (~> 2.5)
    middleman-autoprefixer (2.6.1)
      autoprefixer-rails (~> 6.0.1)
      middleman-core (>= 3.3.3)
    middleman-core (3.4.0)
      activesupport (~> 4.1)
      bundler (~> 1.1)
      capybara (~> 2.4.4)
      erubis
      hooks (~> 0.3)
      i18n (~> 0.7.0)
      listen (~> 3.0.3)
      padrino-helpers (~> 0.12.3)
      rack (>= 1.4.5, < 2.0)
      thor (>= 0.15.2, < 2.0)
      tilt (~> 1.4.1, < 2.0)
    middleman-livereload (3.4.3)
      em-websocket (~> 0.5.1)
      middleman-core (>= 3.3)
      rack-livereload (~> 0.3.15)
    middleman-minify-html (3.4.1)
      htmlcompressor (~> 0.2.0)
      middleman-core (>= 3.2)
    middleman-s3_sync (3.3.3)
      ansi (~> 1.5.0)
      fog-aws (>= 0.1.1)
      map
      middleman-core (~> 3.3)
      parallel
      ruby-progressbar
      unf
    middleman-sprockets (3.4.2)
      middleman-core (>= 3.3)
      sprockets (~> 2.12.1)
      sprockets-helpers (~> 1.1.0)
      sprockets-sass (~> 1.3.0)
    mime-types (2.6.2)
    mini_portile (0.6.2)
    minitest (5.8.1)
    multi_json (1.11.2)
    net-scp (1.2.1)
      net-ssh (>= 2.6.5)
    net-ssh (3.0.1)
    nokogiri (1.6.6.2)
      mini_portile (~> 0.6.0)
    padrino-helpers (0.12.5)
      i18n (~> 0.6, >= 0.6.7)
      padrino-support (= 0.12.5)
      tilt (~> 1.4.1)
    padrino-support (0.12.5)
      activesupport (>= 3.1)
    parallel (1.6.1)
    rack (1.6.4)
    rack-livereload (0.3.16)
      rack
    rack-test (0.6.3)
      rack (>= 1.0)
    rb-fsevent (0.9.6)
    rb-inotify (0.9.5)
      ffi (>= 0.5.0)
    ruby-progressbar (1.7.5)
    sass (3.4.19)
    sprockets (2.12.4)
      hike (~> 1.2)
      multi_json (~> 1.0)
      rack (~> 1.0)
      tilt (~> 1.1, != 1.3.0)
    sprockets-helpers (1.1.0)
      sprockets (~> 2.0)
    sprockets-sass (1.3.1)
      sprockets (~> 2.0)
      tilt (~> 1.1)
    thor (0.19.1)
    thread_safe (0.3.5)
    tilt (1.4.1)
    tzinfo (1.2.2)
      thread_safe (~> 0.1)
    uber (0.0.15)
    uglifier (2.7.2)
      execjs (>= 0.3.0)
      json (>= 1.8.0)
    unf (0.1.4)
      unf_ext
    unf_ext (0.0.7.1)
    xpath (2.0.0)
      nokogiri (~> 1.3)

PLATFORMS
  ruby

DEPENDENCIES
  bootstrap-sass
  middleman
  middleman-autoprefixer
  middleman-livereload
  middleman-minify-html
  middleman-s3_sync

BUNDLED WITH
   1.10.6
```

And my config is like so:

```ruby
# directories
set :css_dir,    'styles'
set :js_dir,     'scripts'
set :images_dir, 'images'

activate :autoprefixer do |config|
  config.browsers = ['last 2 versions']
end

# Reload the browser automatically whenever files change
configure :development do
  activate :livereload
end

# Build-specific configuration
configure :build do
  activate :asset_hash
  activate :gzip
  activate :minify_css
  activate :minify_javascript
  activate :minify_html do |html|
    html.simple_doctype = true
  end
end

# Setup sync to run after build.
activate :s3_sync do |s3_sync|
  s3_sync.bucket      = 'XXX'
  s3_sync.region      = 'us-east-1'
  s3_sync.delete      = false
  s3_sync.after_build = true
  s3_sync.prefer_gzip = true

  # Testing prefix.
  s3_sync.prefix = '_test'
end

#
# Set up our caching policy:
#   - HTML should always revalidate
#   - CSV should last 24 hours and be public
#   - Everything else should max out and be public
#
caching_policy 'text/html', max_age: 0, must_revalidate: true

# Cache CSV for 24 hours
caching_policy 'text/comma-separated-values', max_age: (60 * 60 * 24), public: true

# Default caching policy is to keep it around for a year.
default_caching_policy max_age: (60 * 60 * 24 * 365), public: true
```

I'm a little confused why it gets part way through, but it always bails after doing some amount of work and I often end up with some weird partial content on S3.

Any help would be awesome, thanks!

**Comment by fredjean** [comment]
I'll have a look at it tonight.

**Comment by fredjean** [comment]
This error happens when the after_build setting is set to true. The @app variable is nil at this point, which causes the run_hook call to fail. I have a fix for that issue in master.

However, I am not able to make sure that s3_sync is called after all the other extensions. As a result, I don't recommend setting after_build to true, but instead run `middleman s3_sync` as a separate step.

Is it possible to provide the bucket name so I can have a look at the site? I am curious about what you mean by partial content.

**Comment by evanleck** [comment]
Ah, yeah I was using the `after_build` option. Makes sense, thanks for clearing that up!

I had to overwrite the partial content stuff (I was getting a 204 from S3 on certain objects) because it was causing problems for customers so I don't have a current link you could check. If you'd like, I can try and reproduce it and get you a link. Would that be helpful?

**Comment by evanleck** [comment]
Also, I just was looking through the docs for Middleman and found this [after_build](https://middlemanapp.com/advanced/custom_extensions/#after_build) hook that might be useful.

**Comment by fredjean** [comment]
You can pass -b <name-of-bucker> to s3_sync as a way to push content to
a separate bucket. It would allow you to push content somewhere else and
I could have a look there.

However, the 204 is a response that I have yet to come across... I'll
have to think of a way to reproduce it.

-- Fred

Evan wrote:

**Comment by fredjean** [comment]
Yes, we are using the after_build hook if you set the s3_sync's
after_build option to true. I am having difficulties controlling the
order of the plugins in my tests though. I am considering submitting a
PR to MM to add another hook when it is ready to publish.

-- Fred

Evan wrote:

**Comment by evanleck** [comment]
I can't seem to reproduce the 204 issue, maybe it was a fluke?

**Comment by fredjean** [comment]
Fluke happen... As a note, it appears that the after_build hook is going away with MM4. We already have a solution in place for that release. I'll see if it's available under MM 3.x.
